name: exercise_13
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8 
  - numpy=1.23.4
  - protobuf=3.20.0
  - pandas=1.2.3
  - pip=20.3.3
  - scikit-learn=0.24.1
  - matplotlib=3.2.2
  - plotly=4.4.1
  - pillow=8.1.2
  - mlflow=1.14.1
  - pip:
      - wandb==0.13.3
      - omegaconf==2.0.6